CREATE TABLE admins (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	first_name VARCHAR(30) NOT NULL,
	last_name VARCHAR(30) NOT NULL,
	email VARCHAR(40) NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE categories (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	name VARCHAR(50)
);

CREATE TABLE products (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	title VARCHAR(100) NOT NULL,
	description TEXT,
	price DECIMAL(5, 2) NOT NULL CHECK(price > 0.00),
	category INT REFERENCES categories(id) 
	ON DELETE CASCADE 
	ON UPDATE CASCADE
	NOT NULL,
	image TEXT NOT NULL
);



